[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = [
  'npm run build --if-present',
  'cd client && npm install && npm run build'
]

[start]
cmd = 'node runtime-manager.js'